---
# PLAYBOOK ANSIBLE - Installation d'Apache
# Un playbook = une liste de "plays" (tâches à exécuter)

- name: Installer et configurer Apache sur le container
  # "name" = description de ce que fait ce play

  hosts: all
  # "hosts: all" = exécute sur tous les hôtes dans l'inventaire
  # Terraform passera l'IP du container créé comme inventaire

  become: yes
  # "become: yes" = utilise sudo (exécute en tant que root)
  # Nécessaire pour installer des paquets

  tasks:
    # "tasks" = liste des tâches à exécuter dans l'ordre

    - name: S'assurer que SSH est installé et actif
      # Première tâche : vérifier que SSH fonctionne
      apt:
        # Module "apt" = gère les paquets Debian/Ubuntu
        name: openssh-server
        # Nom du paquet à installer
        state: present
        # "present" = s'assurer que le paquet est installé
        # Si déjà installé, ne fait rien

    - name: Mettre à jour le cache apt
      # Équivalent de : apt-get update
      apt:
        update_cache: yes
        # Télécharge la liste des paquets disponibles
        cache_valid_time: 3600
        # Cache valide pendant 3600 secondes (1h)
        # Si mis à jour il y a moins d'1h, ne refait pas l'update

    - name: Installer Apache2
      # Installation du serveur web Apache
      apt:
        name: apache2
        # Nom du paquet Apache
        state: present
        # S'assurer qu'il est installé

    - name: Démarrer et activer Apache
      # Démarre Apache maintenant ET au démarrage du système
      systemd:
        # Module "systemd" = gère les services systemd
        name: apache2
        # Nom du service
        state: started
        # "started" = démarre le service s'il n'est pas démarré
        enabled: yes
        # "enabled: yes" = démarre automatiquement au boot

    - name: Créer une page d'accueil personnalisée
      # Remplace la page par défaut d'Apache
      copy:
        # Module "copy" = copie du contenu vers un fichier
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Container {{ ansible_hostname }}</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      margin: 50px;
                      background: #f0f0f0;
                  }
                  .container {
                      background: white;
                      padding: 30px;
                      border-radius: 10px;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  }
                  h1 { color: #0066cc; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 Bienvenue sur le serveur Apache</h1>
                  <p><strong>Hostname:</strong> {{ ansible_hostname }}</p>
                  <p><strong>IP:</strong> {{ ansible_default_ipv4.address }}</p>
                  <p><strong>OS:</strong> {{ ansible_distribution }} {{ ansible_distribution_version }}</p>
                  <hr>
                  <p>✅ Déployé automatiquement avec <strong>Terraform</strong> + <strong>Ansible</strong></p>
              </div>
          </body>
          </html>
        # Le contenu HTML ci-dessus sera écrit dans le fichier
        # {{ ansible_hostname }}, etc. = variables Ansible (facts)
        # Ansible collecte automatiquement ces infos sur l'hôte
        dest: /var/www/html/index.html
        # Chemin de destination du fichier
        # C'est la page par défaut d'Apache

    - name: Ouvrir le port 80 dans le firewall (si UFW actif)
      # Optionnel : ouvre le port HTTP si un firewall est actif
      ufw:
        rule: allow
        port: '80'
        proto: tcp
      ignore_errors: yes
      # "ignore_errors: yes" = continue même si UFW n'est pas installé

    - name: Vérifier le statut d'Apache
      # Vérifie qu'Apache fonctionne correctement
      systemd:
        name: apache2
        state: started
      register: apache_status
      # "register" = sauvegarde le résultat dans une variable

    - name: Afficher le statut d'Apache
      # Affiche un message dans la console
      debug:
        # Module "debug" = affiche des informations
        msg: "✅ Apache est {{ 'actif' if apache_status.status.ActiveState == 'active' else 'inactif' }}"
        # Utilise la variable "apache_status" de la tâche précédente

    - name: Afficher l'URL d'accès
      # Informe l'utilisateur comment accéder au serveur
      debug:
        msg: "🌐 Accédez à votre serveur : http://{{ ansible_default_ipv4.address }}"
        # ansible_default_ipv4.address = IP du container
